[package]
name = "finance_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = [ "postgres", "runtime-tokio", "tls-native-tls" ] }
tokio = { version = "1.41.0", features = ["full"] }
