[package]
name = "finance_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.93"
dotenv = "0.15.0"
serde = "1.0.215"
sqlx = { version = "0.8.2", features = [ "postgres"] }
tokio = { version = "1.41.1", features = ["full"] }
